import OpenUSD

public enum USDCLayerFieldValue: Sendable, Equatable {
    case unmaterializedValue(USDCUnmaterializedValue)
    case timeSamples([SdfTimeSample])
    case bool(Bool)
    case boolArray([Bool])
    case token(String)
    case tokenArray([String])
    case tokenVector([String])
    case string(String)
    case stringVector([String])
    case assetPath(String)
    case dictionary([String: USDCLayerFieldValue])
    case pathVector([String])
    case variantSelectionMap([String: String])
    case tokenListOperation(USDCListOperation<String>)
    case stringListOperation(USDCListOperation<String>)
    case pathListOperation(USDCListOperation<String>)
    case referenceListOperation(USDCListOperation<USDCReference>)
    case payloadListOperation(USDCListOperation<USDCPayload>)
    case payload(USDCPayload)
    case int(Int)
    case double(Double)
    case doubleArray([Double])
    case doubleVector([Double])
    case intArray([Int])
    case timeCode(Double)
    case timeCodeArray([Double])
    case point2(USDPoint2D)
    case point2Array([USDPoint2D])
    case point3(USDPoint3D)
    case point3Array([USDPoint3D])
    case layerOffsetVector([SdfLayerOffset])
    case permission(SdfPermission)
    case variability(SdfVariability)
    case specifier(SdfSpecifier)
}
