import OpenUSD

public enum USDCLayerFieldValue: Sendable, Equatable {
    case bool(Bool)
    case boolArray([Bool])
    case token(String)
    case tokenArray([String])
    case tokenVector([String])
    case string(String)
    case assetPath(String)
    case dictionary([String: USDCLayerFieldValue])
    case pathVector([String])
    case tokenListOperation(USDCListOperation<String>)
    case stringListOperation(USDCListOperation<String>)
    case pathListOperation(USDCListOperation<String>)
    case referenceListOperation(USDCListOperation<USDCReference>)
    case payloadListOperation(USDCListOperation<USDCPayload>)
    case payload(USDCPayload)
    case int(Int)
    case double(Double)
    case doubleArray([Double])
    case intArray([Int])
    case point2(USDPoint2D)
    case point2Array([USDPoint2D])
    case specifier(USDCPrimSpecifier)
}
